triggers:
  - name: triggerwoo1
    type: trigger
    source:
      message: 'testing trigger in yml'
      
  - name: triggerwoo2
    type: trigger
    source:
      message: 'testing job trigger in yml'
      
  - name: triggerwoo3
    type: trigger
    source:
      message: 'testing job trigger in yml ecs replica0'
