triggers:
  - name: triggerone
    type: trigger
    source:
      message: 'testing ecs jobtrigger in yml'
      
  - name: triggertwo
    type: trigger
    source:
      counter: 8
      
  - name: triggerthree
    type: trigger
    source:
      counter: 1
