triggers:
  - name: triggerone
    type: trigger
    source:
      message: 'testing ecs job trigger in yml'
      
  - name: triggertwo
    type: trigger
    source:
      counter: 5
      
  - name: triggerthree
    type: trigger
    source:
      counter: 1
