triggers:
  - name: triggerwoo1
    type: trigger
    source:
      message: 'testing trigger in yml'
      
  - name: triggerwoo2
    type: trigger
    source:
      message: 'testing jobtrigger in yml'
