triggers:
  - name: triggerone
    type: trigger
    source:
      message: 'testing trigger in yml'
      
  - name: triggertwo
    type: trigger
    source:
      counter: 1
      
  - name: triggerthree
    type: trigger
    source:
      counter: 1
