triggers:
  - name: triggerwoo1
    type: trigger
    source:
      message: 'testing trigger in yml'
      
  - name: triggerwoo2
    type: trigger
    source:
      message: 'testing job trigger in yml'
      
  - name: triggerwoo3
    type: trigger
    source:
      message: 'testing job trigger in yml ecs deploy with replica0'
      
  - name: triggerwoo4
    type: trigger
    source:
      message: 'testing job trigger in yml ecs deploy error handling for port number'
